Ajoute l'intégration continue
betagouv/mes-aides-analytics pull request #42
Opened 2023-02-27 11:20 UTC by Shamzic

2023-03-23 13:42 UTC, Shamzic commented on .github/workflows/cd.yml
> +name: Continuous deployment to github pages https://betagouv.github.io/mes-aides-analytics/ v0.1.0
> Pourquoi spécifier le numéro de version `v0.1.0` ?

Etant donné que la CI va évoluer plus tard, je me suis dit qu'ajouter un numéro de version pourrait expliciter la chose, mais effectivement, si c'est ce que tu sous-entends, c'est plus de la déco qu'autre chose dans cette chaîne de caractères. Je retire ça.

2023-03-27 16:09 UTC, baptou12 commented on .github/workflows/ci.yml
> +        run: npm run prettier:check
C'est voulu de ne pas mettre aussi une action `npm run lint`, sinon je rajouterais bien ça aussi

2023-03-27 16:10 UTC, baptou12 requested changes
Au moins une question

2023-03-28 07:40 UTC, Shamzic commented on .github/workflows/ci.yml
> +        run: npm run prettier:check
Oui c'était voulu dans la description de la tâche (`En V0 faire un npm install et npm build`), mais je tout à fait l'ajouter car ça ne coûte pas grand chose 👍

2023-03-28 08:07 UTC, baptou12 commented on .eslintrc.js
> +    "no-unused-vars": "off", //["error", { argsIgnorePattern: "next" }],
Je pense tu peux enlever le comment après. 

PS: je trouve ça dommage d'avoir cette règle off, mais c'était le cas avant, p.e. dans un autre ticket.

2023-03-28 08:08 UTC, baptou12 requested changes
Virer le comment dans `eslintrc.js` sinon all good pour moi on peut merge après ça

2023-03-28 14:30 UTC, Shamzic commented on .eslintrc.js
> +    "no-unused-vars": "off", //["error", { argsIgnorePattern: "next" }],
J'ai remis la règle et modifié les fichiers avec les variables inutilisées en conséquence

2023-03-28 14:32 UTC, Shamzic commented
J'ai ajouté Eslint à la CI, mis à jour la version de React dans les paramètres de la config Eslint, mis à jour les règles utilisées et corrigé les erreurs eslint présentes dans certains fichiers

2023-03-28 16:57 UTC, baptou12 approved these changes

2023-03-31 10:31 UTC, merged