Add loader
betagouv/mes-aides-analytics pull request #64
Opened 2023-05-16 13:52 UTC by baptou12

2023-05-19 13:54 UTC, Shamzic requested changes

2023-05-19 13:54 UTC, Shamzic commented on pages/behaviours.js
> +                DataFilter.DEFAULT_INSTITUTION) && (
Même remarque que pour le fichier `components/surveyDetails.js`

2023-05-22 09:10 UTC, baptou12 commented on components/undisplayedBenefits.jsx
Je vais tout laisser en JS, selon moi on devrait avoir tout les composant ayant des tag html en jsx mais c'est pas mandatory apparement, à voir ce qu'on veut faire

2023-05-24 13:14 UTC, Shamzic approved these changes
Tourne bien en local, pour moi c'est clean

2023-05-24 13:45 UTC, merged

2023-05-24 13:52 UTC, baptou12 commented
@Shamzic Je viens de mettre en prod, mais  je me suis rendu compte qu'il y avait encore un soucis : https://trello.com/c/BO1ITQ6F/1304-probl%C3%A8me-chargement-page-behaviour-de-mes-aides-analytics

Pas d'urgence, mais on pourra le prio