1355 tunnel de conversion de bout en bout juin 2023
betagouv/mes-aides-analytics pull request #95
Opened 2023-07-20 14:08 UTC by baptou12

Commencement de la tâche, le front est quasi fait, il manque d'aller chercher la vrai donnée. A priori je vais mettre ça dans aides-jeunes car la connexion à la db pour certaines métriques se trouve là bas.

2023-07-20 14:38 UTC, baptou12 commented on services/funnelService.js
> +export const fetchFunnelData = async (month) => {
Fichier temporaire, pas encore à review

2023-07-27 13:47 UTC, Shamzic commented
Problème à l'accès de la page `/funnel` :

![image](https://github.com/betagouv/mes-aides-analytics/assets/18016058/bb64a018-e8ae-4acd-9317-9d6e3887f6b2)

2023-07-27 13:57 UTC, Shamzic commented on services/funnelService.js
> +  const funnelData = statsResponse.funnel
Pour tester, j'ai remplacé le fetch ici par un [objet en dur](https://github.com/betagouv/mes-aides-analytics/blob/1f52a3d7613c613386ee8c7d81a640c116679c94/cypress/fixtures/aidesJeunesStatistics.json#L109-L121) car actuellement l'objet renvoyé par https://mes-aides.1jeune1solution.beta.gouv.fr/documents/stats.json n'a pas encore la clef `funnel`. Tu as testé avec un lien en pré-prod ou objet hébergé ailleurs j'imagine ?

2023-07-27 15:03 UTC, Shamzic requested changes

2023-08-17 14:02 UTC, baptou12 commented on public/static/style.css
> +  min-height: 4rem;
Oui je me souvient plus du pourquoi, en l'enlevant je ne vois pas vraiment de soucis UI

2023-08-17 14:04 UTC, baptou12 commented on public/static/style.css
> +}
Ok même comportement, je pense que la lib souhaite qu'on explicite les largeur un peu plus pour gérer le redimensionnement. J'ai repris ta solution et j'ai effectivement plus le soucis ! Merci !

2023-08-17 14:36 UTC, merged